package com.linkbyte.everscript;

enum TokenType {
  // Single char tokens
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS, PLUS,
  SEMICOLON, SLASH, STAR, MODULO,

  // One to two char tokens
  LEFT_SHIFT, RIGHT_SHIFT,
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  ARROW, REVERSE_ARROW,
  COLON, COLON_COLON,
  MINUS_MINUS, PLUS_PLUS,
  QUESTION, OPTIONAL_CHAINING,
  FAT_ARROW, PIPE, PIPE_PIPE,
  AMPERSAND, AMPERSAND_AMPERSAND,
  XOR, EXPONENTIATION,

  // Literals
  IDENTIFIER, STRING, NUMBER,

  // Keywords
  AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR, RETURN,
  SUPER, THIS, TRUE, VAR, WHILE, IMPLEMENTS, STATIC, IMPORT,
  TRY, CATCH, FINALLY, THROW, INHERITS, ENUM, AS, CONST, TRAIT,
  ABSTRACT, PRIVATE, NATIVE, MATCH, CASE, OTHER, INSTANCEOF,

  EOF
}
