package com.linkbyte.everscript;

enum TokenType {
  // Single char tokens
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS, PLUS,
  SEMICOLON, SLASH, STAR,

  // One to two char tokens
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  ARROW, REVERSE_ARROW,
  COLON, COLON_COLON,
  MINUS_MINUS, PLUS_PLUS,
  QUESTION, OPTIONAL_CHAINING,
  FAT_ARROW,

  // Literals
  IDENTIFIER, STRING, NUMBER,

  // Keywords
  AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR, PRINT, RETURN,
  SUPER, THIS, TRUE, VAR, WHILE, IMPLEMENTS, STATIC, IMPORT,
  TRY, CATCH, FINALLY, THROW, INHERITS, ENUM, AS, CONST, TRAIT,
  ABSTRACT, PRIVATE, NATIVE,

  EOF
}
